// flow-typed signature: 8749bc5669ab1ae917fef403c1eb5684
// flow-typed version: <<STUB>>/callsite-record_v^3.2.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'callsite-record'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'callsite-record' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'callsite-record/lib/index' {
  declare module.exports: any;
}

declare module 'callsite-record/lib/renderers/default' {
  declare module.exports: any;
}

declare module 'callsite-record/lib/renderers/html' {
  declare module.exports: any;
}

declare module 'callsite-record/lib/renderers/no-color' {
  declare module.exports: any;
}

// Filename aliases
declare module 'callsite-record/lib/index.js' {
  declare module.exports: $Exports<'callsite-record/lib/index'>;
}
declare module 'callsite-record/lib/renderers/default.js' {
  declare module.exports: $Exports<'callsite-record/lib/renderers/default'>;
}
declare module 'callsite-record/lib/renderers/html.js' {
  declare module.exports: $Exports<'callsite-record/lib/renderers/html'>;
}
declare module 'callsite-record/lib/renderers/no-color.js' {
  declare module.exports: $Exports<'callsite-record/lib/renderers/no-color'>;
}
