// flow-typed signature: 90c9d56005842f857d5a3de2988d7b07
// flow-typed version: <<STUB>>/co_v^4.6.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'co'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'co' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'co/index' {
  declare module.exports: $Exports<'co'>;
}
declare module 'co/index.js' {
  declare module.exports: $Exports<'co'>;
}
