// flow-typed signature: bea0817d456598362fafa8ff1e64e15f
// flow-typed version: <<STUB>>/depcheck_v^0.6.7/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'depcheck'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'depcheck' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'depcheck/dependent-build/depcheck-test-e2e/e2e' {
  declare module.exports: any;
}

declare module 'depcheck/dependent-build/depcheck-test-e2e/fake_modules/good/index' {
  declare module.exports: any;
}

declare module 'depcheck/dependent-build/depcheck-test-e2e/fake_modules/missing/index' {
  declare module.exports: any;
}

declare module 'depcheck/dependent-build/depcheck-test-e2e/fake_modules/unused/index' {
  declare module.exports: any;
}

declare module 'depcheck/dist/check' {
  declare module.exports: any;
}

declare module 'depcheck/dist/cli' {
  declare module.exports: any;
}

declare module 'depcheck/dist/constants' {
  declare module.exports: any;
}

declare module 'depcheck/dist/detector/gruntLoadTaskCallExpression' {
  declare module.exports: any;
}

declare module 'depcheck/dist/detector/importDeclaration' {
  declare module.exports: any;
}

declare module 'depcheck/dist/detector/requireCallExpression' {
  declare module.exports: any;
}

declare module 'depcheck/dist/index' {
  declare module.exports: any;
}

declare module 'depcheck/dist/parser/coffee' {
  declare module.exports: any;
}

declare module 'depcheck/dist/parser/es6' {
  declare module.exports: any;
}

declare module 'depcheck/dist/parser/es7' {
  declare module.exports: any;
}

declare module 'depcheck/dist/parser/jsx' {
  declare module.exports: any;
}

declare module 'depcheck/dist/parser/sass' {
  declare module.exports: any;
}

declare module 'depcheck/dist/parser/typescript' {
  declare module.exports: any;
}

declare module 'depcheck/dist/special/babel' {
  declare module.exports: any;
}

declare module 'depcheck/dist/special/bin' {
  declare module.exports: any;
}

declare module 'depcheck/dist/special/commitizen' {
  declare module.exports: any;
}

declare module 'depcheck/dist/special/eslint' {
  declare module.exports: any;
}

declare module 'depcheck/dist/special/feross-standard' {
  declare module.exports: any;
}

declare module 'depcheck/dist/special/gulp-load-plugins' {
  declare module.exports: any;
}

declare module 'depcheck/dist/special/mocha' {
  declare module.exports: any;
}

declare module 'depcheck/dist/special/webpack' {
  declare module.exports: any;
}

declare module 'depcheck/dist/utils/get-scripts' {
  declare module.exports: any;
}

declare module 'depcheck/dist/utils/index' {
  declare module.exports: any;
}

declare module 'depcheck/false-alert' {
  declare module.exports: any;
}

// Filename aliases
declare module 'depcheck/dependent-build/depcheck-test-e2e/e2e.js' {
  declare module.exports: $Exports<'depcheck/dependent-build/depcheck-test-e2e/e2e'>;
}
declare module 'depcheck/dependent-build/depcheck-test-e2e/fake_modules/good/index.js' {
  declare module.exports: $Exports<'depcheck/dependent-build/depcheck-test-e2e/fake_modules/good/index'>;
}
declare module 'depcheck/dependent-build/depcheck-test-e2e/fake_modules/missing/index.js' {
  declare module.exports: $Exports<'depcheck/dependent-build/depcheck-test-e2e/fake_modules/missing/index'>;
}
declare module 'depcheck/dependent-build/depcheck-test-e2e/fake_modules/unused/index.js' {
  declare module.exports: $Exports<'depcheck/dependent-build/depcheck-test-e2e/fake_modules/unused/index'>;
}
declare module 'depcheck/dist/check.js' {
  declare module.exports: $Exports<'depcheck/dist/check'>;
}
declare module 'depcheck/dist/cli.js' {
  declare module.exports: $Exports<'depcheck/dist/cli'>;
}
declare module 'depcheck/dist/constants.js' {
  declare module.exports: $Exports<'depcheck/dist/constants'>;
}
declare module 'depcheck/dist/detector/gruntLoadTaskCallExpression.js' {
  declare module.exports: $Exports<'depcheck/dist/detector/gruntLoadTaskCallExpression'>;
}
declare module 'depcheck/dist/detector/importDeclaration.js' {
  declare module.exports: $Exports<'depcheck/dist/detector/importDeclaration'>;
}
declare module 'depcheck/dist/detector/requireCallExpression.js' {
  declare module.exports: $Exports<'depcheck/dist/detector/requireCallExpression'>;
}
declare module 'depcheck/dist/index.js' {
  declare module.exports: $Exports<'depcheck/dist/index'>;
}
declare module 'depcheck/dist/parser/coffee.js' {
  declare module.exports: $Exports<'depcheck/dist/parser/coffee'>;
}
declare module 'depcheck/dist/parser/es6.js' {
  declare module.exports: $Exports<'depcheck/dist/parser/es6'>;
}
declare module 'depcheck/dist/parser/es7.js' {
  declare module.exports: $Exports<'depcheck/dist/parser/es7'>;
}
declare module 'depcheck/dist/parser/jsx.js' {
  declare module.exports: $Exports<'depcheck/dist/parser/jsx'>;
}
declare module 'depcheck/dist/parser/sass.js' {
  declare module.exports: $Exports<'depcheck/dist/parser/sass'>;
}
declare module 'depcheck/dist/parser/typescript.js' {
  declare module.exports: $Exports<'depcheck/dist/parser/typescript'>;
}
declare module 'depcheck/dist/special/babel.js' {
  declare module.exports: $Exports<'depcheck/dist/special/babel'>;
}
declare module 'depcheck/dist/special/bin.js' {
  declare module.exports: $Exports<'depcheck/dist/special/bin'>;
}
declare module 'depcheck/dist/special/commitizen.js' {
  declare module.exports: $Exports<'depcheck/dist/special/commitizen'>;
}
declare module 'depcheck/dist/special/eslint.js' {
  declare module.exports: $Exports<'depcheck/dist/special/eslint'>;
}
declare module 'depcheck/dist/special/feross-standard.js' {
  declare module.exports: $Exports<'depcheck/dist/special/feross-standard'>;
}
declare module 'depcheck/dist/special/gulp-load-plugins.js' {
  declare module.exports: $Exports<'depcheck/dist/special/gulp-load-plugins'>;
}
declare module 'depcheck/dist/special/mocha.js' {
  declare module.exports: $Exports<'depcheck/dist/special/mocha'>;
}
declare module 'depcheck/dist/special/webpack.js' {
  declare module.exports: $Exports<'depcheck/dist/special/webpack'>;
}
declare module 'depcheck/dist/utils/get-scripts.js' {
  declare module.exports: $Exports<'depcheck/dist/utils/get-scripts'>;
}
declare module 'depcheck/dist/utils/index.js' {
  declare module.exports: $Exports<'depcheck/dist/utils/index'>;
}
declare module 'depcheck/false-alert.js' {
  declare module.exports: $Exports<'depcheck/false-alert'>;
}
