// flow-typed signature: c9a8ab0b91c15ca33d2e7f2b5c3a0905
// flow-typed version: <<STUB>>/giturl_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'giturl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'giturl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'giturl/lib/giturl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'giturl/index' {
  declare module.exports: $Exports<'giturl'>;
}
declare module 'giturl/index.js' {
  declare module.exports: $Exports<'giturl'>;
}
declare module 'giturl/lib/giturl.js' {
  declare module.exports: $Exports<'giturl/lib/giturl'>;
}
