// flow-typed signature: a3c8aea7a6152f1e4e317b8a5051c601
// flow-typed version: <<STUB>>/global-modules_v^0.2.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'global-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'global-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'global-modules/index' {
  declare module.exports: $Exports<'global-modules'>;
}
declare module 'global-modules/index.js' {
  declare module.exports: $Exports<'global-modules'>;
}
