// flow-typed signature: 1f6966a26cedec084779355ad394960a
// flow-typed version: <<STUB>>/globby_v^6.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'globby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'globby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'globby/index' {
  declare module.exports: $Exports<'globby'>;
}
declare module 'globby/index.js' {
  declare module.exports: $Exports<'globby'>;
}
