// flow-typed signature: 2efb8cf98547715132624c414be8e965
// flow-typed version: <<STUB>>/inquirer_v^3.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inquirer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inquirer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inquirer/lib/inquirer' {
  declare module.exports: any;
}

declare module 'inquirer/lib/objects/choice' {
  declare module.exports: any;
}

declare module 'inquirer/lib/objects/choices' {
  declare module.exports: any;
}

declare module 'inquirer/lib/objects/separator' {
  declare module.exports: any;
}

declare module 'inquirer/lib/prompts/base' {
  declare module.exports: any;
}

declare module 'inquirer/lib/prompts/checkbox' {
  declare module.exports: any;
}

declare module 'inquirer/lib/prompts/confirm' {
  declare module.exports: any;
}

declare module 'inquirer/lib/prompts/editor' {
  declare module.exports: any;
}

declare module 'inquirer/lib/prompts/expand' {
  declare module.exports: any;
}

declare module 'inquirer/lib/prompts/input' {
  declare module.exports: any;
}

declare module 'inquirer/lib/prompts/list' {
  declare module.exports: any;
}

declare module 'inquirer/lib/prompts/password' {
  declare module.exports: any;
}

declare module 'inquirer/lib/prompts/rawlist' {
  declare module.exports: any;
}

declare module 'inquirer/lib/ui/baseUI' {
  declare module.exports: any;
}

declare module 'inquirer/lib/ui/bottom-bar' {
  declare module.exports: any;
}

declare module 'inquirer/lib/ui/prompt' {
  declare module.exports: any;
}

declare module 'inquirer/lib/utils/events' {
  declare module.exports: any;
}

declare module 'inquirer/lib/utils/paginator' {
  declare module.exports: any;
}

declare module 'inquirer/lib/utils/readline' {
  declare module.exports: any;
}

declare module 'inquirer/lib/utils/screen-manager' {
  declare module.exports: any;
}

declare module 'inquirer/lib/utils/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inquirer/lib/inquirer.js' {
  declare module.exports: $Exports<'inquirer/lib/inquirer'>;
}
declare module 'inquirer/lib/objects/choice.js' {
  declare module.exports: $Exports<'inquirer/lib/objects/choice'>;
}
declare module 'inquirer/lib/objects/choices.js' {
  declare module.exports: $Exports<'inquirer/lib/objects/choices'>;
}
declare module 'inquirer/lib/objects/separator.js' {
  declare module.exports: $Exports<'inquirer/lib/objects/separator'>;
}
declare module 'inquirer/lib/prompts/base.js' {
  declare module.exports: $Exports<'inquirer/lib/prompts/base'>;
}
declare module 'inquirer/lib/prompts/checkbox.js' {
  declare module.exports: $Exports<'inquirer/lib/prompts/checkbox'>;
}
declare module 'inquirer/lib/prompts/confirm.js' {
  declare module.exports: $Exports<'inquirer/lib/prompts/confirm'>;
}
declare module 'inquirer/lib/prompts/editor.js' {
  declare module.exports: $Exports<'inquirer/lib/prompts/editor'>;
}
declare module 'inquirer/lib/prompts/expand.js' {
  declare module.exports: $Exports<'inquirer/lib/prompts/expand'>;
}
declare module 'inquirer/lib/prompts/input.js' {
  declare module.exports: $Exports<'inquirer/lib/prompts/input'>;
}
declare module 'inquirer/lib/prompts/list.js' {
  declare module.exports: $Exports<'inquirer/lib/prompts/list'>;
}
declare module 'inquirer/lib/prompts/password.js' {
  declare module.exports: $Exports<'inquirer/lib/prompts/password'>;
}
declare module 'inquirer/lib/prompts/rawlist.js' {
  declare module.exports: $Exports<'inquirer/lib/prompts/rawlist'>;
}
declare module 'inquirer/lib/ui/baseUI.js' {
  declare module.exports: $Exports<'inquirer/lib/ui/baseUI'>;
}
declare module 'inquirer/lib/ui/bottom-bar.js' {
  declare module.exports: $Exports<'inquirer/lib/ui/bottom-bar'>;
}
declare module 'inquirer/lib/ui/prompt.js' {
  declare module.exports: $Exports<'inquirer/lib/ui/prompt'>;
}
declare module 'inquirer/lib/utils/events.js' {
  declare module.exports: $Exports<'inquirer/lib/utils/events'>;
}
declare module 'inquirer/lib/utils/paginator.js' {
  declare module.exports: $Exports<'inquirer/lib/utils/paginator'>;
}
declare module 'inquirer/lib/utils/readline.js' {
  declare module.exports: $Exports<'inquirer/lib/utils/readline'>;
}
declare module 'inquirer/lib/utils/screen-manager.js' {
  declare module.exports: $Exports<'inquirer/lib/utils/screen-manager'>;
}
declare module 'inquirer/lib/utils/utils.js' {
  declare module.exports: $Exports<'inquirer/lib/utils/utils'>;
}
