// flow-typed signature: b8021575fabae47c3c8ce27556abf313
// flow-typed version: <<STUB>>/merge-options_v0.0.64/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'merge-options'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'merge-options' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'merge-options/index' {
  declare module.exports: $Exports<'merge-options'>;
}
declare module 'merge-options/index.js' {
  declare module.exports: $Exports<'merge-options'>;
}
