// flow-typed signature: c89721656d4f8687c72db62821f3f61c
// flow-typed version: <<STUB>>/minimatch_v^3.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minimatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'minimatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minimatch/minimatch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minimatch/minimatch.js' {
  declare module.exports: $Exports<'minimatch/minimatch'>;
}
