// flow-typed signature: f0e70c53a9f637801c776fe5c0b3a779
// flow-typed version: <<STUB>>/node-emoji_v^1.5.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-emoji/lib/emoji' {
  declare module.exports: any;
}

declare module 'node-emoji/lib/emojifile' {
  declare module.exports: any;
}

declare module 'node-emoji/lib/emojiparse' {
  declare module.exports: any;
}

declare module 'node-emoji/test/emoji' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-emoji/index' {
  declare module.exports: $Exports<'node-emoji'>;
}
declare module 'node-emoji/index.js' {
  declare module.exports: $Exports<'node-emoji'>;
}
declare module 'node-emoji/lib/emoji.js' {
  declare module.exports: $Exports<'node-emoji/lib/emoji'>;
}
declare module 'node-emoji/lib/emojifile.js' {
  declare module.exports: $Exports<'node-emoji/lib/emojifile'>;
}
declare module 'node-emoji/lib/emojiparse.js' {
  declare module.exports: $Exports<'node-emoji/lib/emojiparse'>;
}
declare module 'node-emoji/test/emoji.js' {
  declare module.exports: $Exports<'node-emoji/test/emoji'>;
}
