// flow-typed signature: 4d28672d8943a153ba49e1e37d0483e1
// flow-typed version: <<STUB>>/package-json_v^2.4.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'package-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'package-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'package-json/index' {
  declare module.exports: $Exports<'package-json'>;
}
declare module 'package-json/index.js' {
  declare module.exports: $Exports<'package-json'>;
}
