// flow-typed signature: 5dc6037fd8d90f6af18fc19a2cbac7ff
// flow-typed version: <<STUB>>/semver-diff_v^2.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semver-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'semver-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'semver-diff/index' {
  declare module.exports: $Exports<'semver-diff'>;
}
declare module 'semver-diff/index.js' {
  declare module.exports: $Exports<'semver-diff'>;
}
