// flow-typed signature: 78ab05f44b48bd667eca48e6234d8637
// flow-typed version: <<STUB>>/text-table_v^0.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'text-table/example/align' {
  declare module.exports: any;
}

declare module 'text-table/example/center' {
  declare module.exports: any;
}

declare module 'text-table/example/dotalign' {
  declare module.exports: any;
}

declare module 'text-table/example/doubledot' {
  declare module.exports: any;
}

declare module 'text-table/example/table' {
  declare module.exports: any;
}

declare module 'text-table/test/align' {
  declare module.exports: any;
}

declare module 'text-table/test/ansi-colors' {
  declare module.exports: any;
}

declare module 'text-table/test/center' {
  declare module.exports: any;
}

declare module 'text-table/test/dotalign' {
  declare module.exports: any;
}

declare module 'text-table/test/doubledot' {
  declare module.exports: any;
}

declare module 'text-table/test/table' {
  declare module.exports: any;
}

// Filename aliases
declare module 'text-table/example/align.js' {
  declare module.exports: $Exports<'text-table/example/align'>;
}
declare module 'text-table/example/center.js' {
  declare module.exports: $Exports<'text-table/example/center'>;
}
declare module 'text-table/example/dotalign.js' {
  declare module.exports: $Exports<'text-table/example/dotalign'>;
}
declare module 'text-table/example/doubledot.js' {
  declare module.exports: $Exports<'text-table/example/doubledot'>;
}
declare module 'text-table/example/table.js' {
  declare module.exports: $Exports<'text-table/example/table'>;
}
declare module 'text-table/index' {
  declare module.exports: $Exports<'text-table'>;
}
declare module 'text-table/index.js' {
  declare module.exports: $Exports<'text-table'>;
}
declare module 'text-table/test/align.js' {
  declare module.exports: $Exports<'text-table/test/align'>;
}
declare module 'text-table/test/ansi-colors.js' {
  declare module.exports: $Exports<'text-table/test/ansi-colors'>;
}
declare module 'text-table/test/center.js' {
  declare module.exports: $Exports<'text-table/test/center'>;
}
declare module 'text-table/test/dotalign.js' {
  declare module.exports: $Exports<'text-table/test/dotalign'>;
}
declare module 'text-table/test/doubledot.js' {
  declare module.exports: $Exports<'text-table/test/doubledot'>;
}
declare module 'text-table/test/table.js' {
  declare module.exports: $Exports<'text-table/test/table'>;
}
