// flow-typed signature: c368e41582606566bfbeca362434e29a
// flow-typed version: <<STUB>>/throat_v^3.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'throat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'throat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'throat/test/browser' {
  declare module.exports: any;
}

declare module 'throat/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'throat/index' {
  declare module.exports: $Exports<'throat'>;
}
declare module 'throat/index.js' {
  declare module.exports: $Exports<'throat'>;
}
declare module 'throat/test/browser.js' {
  declare module.exports: $Exports<'throat/test/browser'>;
}
declare module 'throat/test/index.js' {
  declare module.exports: $Exports<'throat/test/index'>;
}
